<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b style="color: #ff0000">*</b> только латинские буквы, цифры и _ -' => '<b style="color: #ff0000">*</b> only latin letters, numbers, and _ -',
    '<b style="color: #ff0000">*</b> формат module/controller/action<br>site/article - доступ к странице site/article<br>site - доступ к любым action контроллера site' => '<b style="color: #ff0000">*</b> format module/controller/action<br>site/article - access to page site/article<br>site - access to any action in site controller',
    'UserClass должен реализовывать интерфейс developeruz\db_rbac\UserRbacInterface' => 'UserClass must implements developeruz\db_rbac\UserRbacInterface',
    'Добавить новое правило' => 'Add new rule',
    'Добавить роль' => 'Add role',
    'Значение "{field}" содержит недопустимые символы' => '"{field}" value contains invalid characters',
    'Название роли' => 'Title for role',
    'Недостаточно прав' => 'You not allow to access',
    'Необходимо указать класс User в настройках модуля' => 'UserClass params must be set in config file',
    'Новая роль' => 'New role',
    'Новое правило' => 'New rule',
    'Описание' => 'Description',
    'Пользователь не найден' => 'User not found',
    'Правила доступа' => 'Access rules',
    'Правило' => 'Rule',
    'Разрешение с таким именем уже существует' => 'Permission with the same name already exists',
    'Разрешенные доступы' => 'Allowed accesses',
    'Разрешенный доступ' => 'Allowed access',
    'Редактирование' => 'Editing',
    'Редактирование правила' => 'Edit the rule',
    'Редактирование роли' => 'Edit the role',
    'Роль' => 'Role',
    'Роль с таким именем уже существует' => 'Role with the same name already exists',
    'Сохранить' => 'Save',
    'Страница не найдена' => 'Page not found',
    'Текстовое описание' => 'Description',
    'Управление ролями' => 'Managing roles',
    'Управление ролями пользователя' => 'Manage user roles',
];
